blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
   path('',views.post_list,name = 'post_list'),
   path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
   path('post',views.PostListView.as_view(),name='post_list'),
   path('<int:post_id>/share/',views.post_share,name="post_share"),
   path('create',views.post_create,name='post_create'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now = True)
    Updated = models.DateTimeField(auto_now = True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='published')
    
    
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])
    
   
class Meta:
     ordering = ('-publish',)
     
     
     def __str__(self):
         return self.title
         
         
         
         
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
         return 'Comment by {} on {}'.format(self.name,self.post)

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

blog/views.py
from django.shortcuts import redirect, render,get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail

class PostListView(ListView):
    template_name = 'blog/post/list.html'
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    


# Create your views here.
# added new changes
def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = Paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',{'page':page,'posts':posts})
    
    
def post_detail(request,year, month, day, post):
    post = get_object_or_404(Post, slug=post, status = 'published',publish__year = year,publish__month = month, publish__day = day)
    
    comments = post.comments.filter(active=True)
    new_comment = None
    
    if request.method=='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    return render(request,'blog/post/detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})
    
    
def post_create(request):
    post = get_object_or_404(Post)
    if request.method=="POST":
        if form.is_valid():
            form.post = post
            form.save()
            form.save()
            return redirect('/mysite')
    else:
        form = Post()
        
        return render(request,'blog/post/create.html')

    

    
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent=False
    
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],cd['email'],post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject,message,'sabariask1307@gmail.com',[cd['to']])
            sent=True
            
    else:
        form = EmailPostForm()
            
    return render(request, 'blog/post/share.html',{'post':post,'form':form,'sent':sent})

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        {% load static %}
        <link type="text/css" href="{% static 'css/blog.css' %}" rel='stylesheet'>
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
             <h2>Django Project</h2>
             <p>Tecci world</p>
        </div>
        <div>
          
        </div>
    </body>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
</html>

blog/templates/blog/post/create.html
{% extends 'blog/base.html' %}

{% block body %}
  <div>
      <h1>Create a blog</h1>
      <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Create</button>
      </form>
  </div>

{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="main">
       <h1 style="color:red;">{{ post.title }}</h1>
       <p>
          published {{ post.publish }} by {{ post.author }}
       </p>
       <p>
          {{ post.body|linebreaks }}
          <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
       </p>
    </div>
    

    {% with comments.count as total_comments %}
        <h3>
            {{ total_comments }} comment {{ total_comments|pluralize }}
        </h3>
    {% endwith %}
    
    {% for comment in comments %}
        <div class="comment">
            <p>
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    
    
    {% if new_comment %}
         <h2>Your comment has been added.</h2>
    {% else %}
         <h2>Add a new comment</h2>
         <form action="." method="POST">
             {{ comment_form.as_p }}
             {% csrf_token %}
             <p><input type='submit' value="Add Comment"></p>
         </form>
    {% endif %} 
    
       
    
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

{% block title %}My Blog{% endblock %}

{% block content %}
   <div class='main'>
    <h1 class='h1'>Blog Bazaar</h1>
    <hr class="n1">
    {% for post in posts %}
        <h3>
           <a href="{{ post.get_absolute_url }}">
              {{ post.title }}
           </a>
        </h3>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{  post.body | truncatewords:30|linebreaks }}
    
    {% endfor %}
    {% include "pagination.html" with page=posts %}
   </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}
     {% if sent %}
         <h1>E-mail successfully sent</h1>
         <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}</p>
         
     {% else %}
         <h1>Share "{{ post.title }}" by e-mail</h1>
         <form action="." method="POST">
             {{form.as_p }}
             {% csrf_token %}
             <input type="submit" value="send e-mail">
         </form>
         
     {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
          {% if page.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page.previous_page_number }}">Previous</a>
          {% endif %}
          <span class="current">
              Page {{ page.number }} of {{ page.paginator.num_pages }}.
          </span>
          {% if page.has_next %}
             <a href="?page={{ page.next_page_number }}">Next..</a>
             <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
    </span>
 </div>